# Generated by Django 5.2.4 on 2025-08-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Meat', 'Meat'), ('Fish', 'Fish'), ('Veggies', 'Veggies'), ('Grocery', 'Grocery')], default='Grocery', max_length=20),
        ),
    ]
